[Variables]
;-----------------------------------------------------------------------------------------------------------------------
;-- Colors (Temperature hue: 20 / 60 / 100 / 140 / 180 / 220 / 0)
ClockColor = 0,0,0,100
ClockShadowColor = 0,0,0,20
ClockBackgroundColor = 0,0,0,32
TitleColor = 255,255,255,140
TextColor = 255,255,255,100
LineColor = 255,255,255,25
BarActiveColor=233,186,118,60
BarBackColor = 233,186,118,40
GraphBackColor = 233,186,118,20
GraphSeparatorColor = 255,255,255,64
BoxTitleColor = 255,255,255,255
BoxBackgroundColor = 0,0,0,255
FullsizeBoxBackgroundColor = 0,0,0,100
ElementBackgroundColor = 0,255,0,0
MarginBackgroundColor = 255,0,0,0
TemperatureDefault = 255,255,255,128
Temperature1 = 255,199,143,192
Temperature2 = 199,255,143,192
Temperature3 = 143,255,199,192
Temperature4 = 143,199,255,192
Temperature5 = 199,143,255,192
Temperature6 = 255,143,199,192
Temperature7 = 255,142,142,192

;-----------------------------------------------------------------------------------------------------------------------
;-- Fonts
FontFamilyDate=ITC Avant Garde Pro XLt
FontFamilyClock=ITC Avant Garde Pro Bk
FontFamily = Myriad Pro
FontSize = 8
TitleFontCase = Upper
TitleFontStyle = Bold
AntiAlias=1
Direction = Left