[Variables]
;-----------------------------------------------------------------------------------------------------------------------
;-- PerfMon IDs (MaxMB can be found out by using #TODO)
Drive1 = C:
Drive1MaxMB = 544
Drive2 = D:
Drive2MaxMB = 177
Drive3 = E:
Drive3MaxMB = 562
Drive4 = P:
Drive4MaxMB = 562

;-----------------------------------------------------------------------------------------------------------------------
;-- HWiNFO IDs
CurrentDownloadSensorId=0xf000ea00
CurrentDownloadSensorInstance=0x0
CurrentDownloadEntryId=0x8000002
CurrentUploadSensorId=0xf000ea00
CurrentUploadSensorInstance=0x0
CurrentUploadEntryId=0x8000003
GPUSensorId=0xe0002000
GPUSensorInstance=0x0
GPUEntryId=0x1000000
CPUSensorId=0xf0000400
CPUSensorInstance=0x0
CPUEntryId=0x10000ff
SystemSensorId=0xf7067950
SystemSensorInstance=0x0
SystemEntryId=0x1000000
Drive1SensorId=0xf0000100
Drive1SensorInstance=0x0
Drive1EntryId=0x1000001
Drive2SensorId=0xf0000100
Drive2SensorInstance=0x3
Drive2EntryId=0x1000000
Drive3SensorId=0xf0000100
Drive3SensorInstance=0x1
Drive3EntryId=0x1000001
Drive4SensorId=0xf0000100
Drive4SensorInstance=0x2
Drive4EntryId=0x1000001

;-----------------------------------------------------------------------------------------------------------------------
;-- Networks
SpeedTestDL=94.4
SpeedTestUL=33.31
NetAVG=4
FastNet=100

;-----------------------------------------------------------------------------------------------------------------------
;-- Temperatures min and max values
minTemp=0
maxTemp=80