

;-------------------------------

[time0]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=None
FontEffectColor=0,0,0,20
FontColor=255,0,0,255
FontFace=#LocalFontFace#
FontSize=150
AntiAlias=1
ClipString=0

[time1]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=None
FontEffectColor=0,0,0,20
FontColor=#color1#
FontFace=#LocalFontFace#
FontSize=150
AntiAlias=1
ClipString=0

[time2]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=None
FontEffectColor=0,0,0,20
FontColor=#color3#
FontFace=#LocalFontFace#
FontSize=150
AntiAlias=1
ClipString=0

[timeshadow]
StringAlign=Center
StringStyle=Normal
FontColor=#color2#
FontFace=#LocalFontFace#
FontSize=150
AntiAlias=1
ClipString=0

;-------------------------------

[Date1]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=shadow
FontEffectColor=#color2#
FontColor=#color1#
FontFace=#LocalFontFace#
FontSize=25
AntiAlias=1
ClipString=0

;-------------------------------

[Sys1]
StringAlign=right
StringCase=None
StringStyle=Normal
StringEffect=shadow
FontEffectColor=#color2#
FontColor=#color1#
FontFace=#LocalFontFace2#
FontSize=9
AntiAlias=1
ClipString=0

[Sys2]
StringAlign=left
StringCase=None
StringStyle=Normal
StringEffect=shadow
FontEffectColor=#color2#
FontColor=#color1#
FontFace=#LocalFontFace2#
FontSize=9
AntiAlias=1
ClipString=0

;-------------------------------

[playerbuttons]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=None
FontEffectColor=0,0,0,20
FontColor=#color1#
FontFace=Webdings
FontSize=13
AntiAlias=1
ClipString=0

[playerbuttons2]
StringAlign=Center
StringCase=None
StringStyle=Normal
StringEffect=Border
FontEffectColor=0,0,0,100
FontColor=255,255,255,255
FontFace=Webdings
FontSize=13
AntiAlias=1
ClipString=0

;-------------------------------
